# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'push_Notif' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'FirebaseInstanceID'
  pod 'Alamofire'


  # Pods for push_Notif

  target 'push_NotifTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'push_NotifUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
